# 1. Using the tidyverse read in the wine dataset that can be downloaded from our Github repo.
library(tidyverse)

# https://github.com/JackStat/PracticalDataScience/blob/master/data/winemag-data-130k-v2.csv (Links to an external site.)Links to an external site.
wine <- read.csv(file="/Users/eddie/Documents/PracticalDataScience/data/winemag-data-130k-v2.csv",head=TRUE,sep=",")
head(wine)


# If you do not download it make sure you clicke "view raw" and use that url.
# 
# 2. Print out the class of the data set
class(wine)
# 3. Create a dataset called Main that removes the X1 column (the first one)
Main <- select(wine, -X)
# 4. Create a new dataset and filter it down to France for the country
France <-
  filter(Main, country == 'France')
# 5. Use the France data set to explore the data a couple different ways (Sort these tables by the count in descending order)
# 
# a. Print out a summarised table with the count of reviews and the min, mean, and max price.
France %>%
  summarise(
    count = n()
  ,min_price = min(price, na.rm = TRUE)
  ,mean_price = mean(price,na.rm = TRUE)
  ,max_price = max(price, na.rm = TRUE)
  )
# 
# b. Print out the reviews and the min, mean, and max price for every taster_name
France %>%
  group_by(taster_name)%>%
  summarise(
    count = n()
    ,min_price = min(price, na.rm = TRUE)
    ,mean_price = mean(price,na.rm = TRUE)
    ,max_price = max(price, na.rm = TRUE)
  )
# c. Print out the reviews and the min, mean, and max price for every country
France %>%
  group_by(country)%>%
  summarise(
    count = n()
    ,min_price = min(price, na.rm = TRUE)
    ,mean_price = mean(price,na.rm = TRUE)
    ,max_price = max(price, na.rm = TRUE)
  )

# d. Remove any row that does not have a taster_name and print out the reviews and the min, mean, and max price for every variety
France %>%
  filter(!is.na(taster_name))%>%
  group_by(taster_name)%>%
  summarise(
    count = n()
    ,min_price = min(price, na.rm = TRUE)
    ,mean_price = mean(price,na.rm = TRUE)
    ,max_price = max(price, na.rm = TRUE)
  )
# 6. Using the Main execute the following tasks
# 
# a. Reduce the dataset to only include wine reviews that have a description that includes 'tannins' or 'finish' then get a count by variety and print out the top 15 highest counts.
Main %>%
  filter(grepl('tannins|finish', description))%>%
  group_by(variety)%>%
  summarise(
    count = n()
  )%>%
  arrange(desc(count))%>%
  #head(15)
  #filter(row_number() <= 15)
  .[1:15,]
# b. Save a new data.frame called Features that only includes wine with more than 150 reviews. group by the variety and create individual columns that represents the proportion of reviews that have 'tannins', 'finish', 'cherry' and 'plum'
Features <-
  Main%>%
  group_by(variety)$>$
  summarise(
    count = n()
    ,tannins = mean(grepl('tannins', description))
    ,finish = mean(grepl('finish', description))
    ,cherry = mean(grepl('cherry', description))
    ,plum = mean(grepl('plum', description))
    ,rubbery = mean(grepl('rubbery', description))
  )%>%
  filter(count >= 150)
# c. Using Features print out the top 5 varieties proportion for each feature that we searched for (tannins, finish, cherry and plum).
Features%>%
  arrange(desc(cherry))%>%
  .[1:5,]%>%
  select(
    variety
    ,count
    ,rubbery
  )

filter(Main, variety == 'Garnacha')%>%
  group_by(country)%>%
  summarise(
    n()
  )
# d. Remove rows without a taster_name, Create a count for each taster_name and then ungroup and use a mutate to calculate the percentage of reviews generated by each taster. sort the list in descending order by the percentage

Main%>%
  filter(!is.na(taster_name))%>%
  group_by(taster_name)%>%
  summarise(
    count = n()
  )%>%
  ungroup()%>%
  mutate(
    percentage = 100*count/sum(count)
  )%>%
  arrange(desc(percentage))
# 
# 
# Bonus
# 
# Build a model that controls for variety, taster_name, and country and examine if more expensive wines are more likely to get higher points. (use lme4. random effects for variety, taster_name, and country and a fixed effect for price)


library(lme4)

ll <- lmer(points ~ price + (1|variety) + (1|taster_name) + (1|country), data = Main)

summary(ll)

#print out random effects
rr<-ranef(ll)

data.frame(
  taster_name = rownames(rr$taster_name)
  ,score = rr$taster_name[,1]
)%>%arrange(desc(score))

data.frame(
  country = rownames(rr$country)
  ,score = rr$taster_name[,1]
)%>% arrange(desc(score))

data.frame(
  variety = rownames(rr$variety)
  ,score = rr$taster_name[,1]
)%>%arrange(desc(score))





          